version: '3.9'

services:
    db:
        container_name: db
        restart: always
        image: postgres
        ports:
            - 6869::5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=258794613
            - POSTGRES_DB=rentx
        volumes:
            - pgdata:/var/lib/postgresql/data
    # app:
    #     build: .
    #     restart: always
    #     container_name: rentx
    #     ports:
    #         - 3333:3333
    #         - 9229:9229
    #     environment:
    #         - PGHOST=db
    #     volumes:
    #         - .:/usr/app
    #     links:
    #         - db
    #     depends_on:
    #         - db

volumes:
    pgdata:
        driver: local