version: '3.9'

services:
    db:
      container_name: db
      restart: always
      image: postgres
      ports:
          - 5432:5432
      environment:
          - POSTGRES_USER=docker
          - POSTGRES_PASSWORD=258794613
          - POSTGRES_DB=ride-manager
      volumes:
          - pgdata:/data/postgres

    redis:
      image: redis:alpine
      ports:
        - 6379:6379

volumes:
    pgdata:
        driver: local