name: Run Tests

on: [push]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: 258794613
          POSTGRESQL_DATABASE: ride-manager

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Run All Tests
        run: npm run test